<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>hoc</string>
		<string>ses</string>
	</array>
	<key>name</key>
	<string>Neuron</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.line.begin.neuron</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.line.end.neuron</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.line.neuron</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.block.begin.neuron</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\1)\*\/\s?</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.block.end.neuron</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.neuron</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\.|\w)([-+]?((\d+(\.)?\d*)|(\d*(\.)?\d+))([eE][-+]?[0-9]+)?)</string>
			<key>name</key>
			<string>constant.numeric.neuron</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.begin.neuron</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\")</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.end.neuron</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.neuron</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped_char</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant_placeholder</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\')</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.begin.neuron</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\')</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.end.neuron</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.neuron</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped_char</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant_placeholder</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.neuron</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.neuron</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(proc|func)\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(\)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(PI|E|GAMMA|DEG|PHI|FARADAY|R)\b</string>
			<key>name</key>
			<string>constant.numeric.neuron</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\&gt;|\&lt;|\!|\+|\-|\*|\=|\||\&amp;|\^|/|//|\%</string>
			<key>name</key>
			<string>keyword.operator.neuron</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(proc|func|obfunc|print|delete|read|debug|double|em|depvar|eqn|local|localobj|strdef|parallel|help|iterator_statement|create|connect|setpointer|access|insert|uninsert|forall|ifsec|forsec|begintemplate|endtemplate|objectvar|objref|public|external|new)\b</string>
			<key>name</key>
			<string>keyword.other.neuron</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(return|break|continue|stop|if|else|while|for|iterator)\b</string>
			<key>name</key>
			<string>keyword.control.neuron</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(sin|cos|atan|tanh|log|log10|exp|sqrt|int|abs|erf|erfc|atan2|system|prmat|solve|eqinit|plt|axis|plot|plotx|ploty|regraph|symbols|printg|xred|sred|ropen|wopen|xopen|hoc_stdout|chdir|fprint|fscan|sscanf|sprint|graph|graphmode|fmenu|lw|getstr|strcmp|setcolor|startsw|stopsw|object_id|allobjectvars|allobjects|xpanel|xbutton|xcheckbox|xstatebutton|xlabel|xmenu|xvalue|xpvalue|xradiobutton|xfixedvalue|xvarlabel|xslider|boolean_dialog|continue_dialog|string_dialog|doEvents|doNotify|ivoc_style|numarg|argtype|hoc_pointer_|nrn_mallinfo|execute|execute1|load_proc|load_func|load_template|load_file|load_java|unix_mac_pc|show_winio|nrn_load_dll|machine_name|saveaudit|retrieveaudit|coredump_on_error|checkpoint|quit|object_push|object_pop|pwman_place|save_session|print_session|show_errmess_always|execerror|variable_domain|name_declared|use_mcell_ran4|mcell_ran4|mcell_ran4_init|numprocs|myproc|psync|settext|WinExec|secname|units|neuronhome|getcwd|nrnversion|object_pushed|)\b</string>
			<key>name</key>
			<string>support.function.neuron</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(hoc_ac_|float_epsilon|hoc_cross_x_|hoc_cross_y_|default_dll_loaded_|celsius|dt|t|stoprun|secondorder|clamp_resist)\b</string>
			<key>name</key>
			<string>support.variable.neuron</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Deck|File|GUIMath|Glyph|Graph|HBox|List|Matrix|PWManager|Pointer|Random|StringFunctions|SymChooser|TextEditor|Timer|VBox|ValueFieldEditor|Vector)\b</string>
			<key>name</key>
			<string>support.class.neuron</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>constant_placeholder</key>
		<dict>
			<key>match</key>
			<string>\%(-)?([0-9])*(\.[0-9]+)?(f|e|g|d|o|x|c|s)</string>
			<key>name</key>
			<string>constant.other.placeholder.neuron</string>
		</dict>
		<key>escaped_char</key>
		<dict>
			<key>match</key>
			<string>\\b|\\f|\\n|\\r|\\t</string>
			<key>name</key>
			<string>constant.character.escape.neuron</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.neuron</string>
	<key>uuid</key>
	<string>1abe2fa4-9b05-4f00-967b-34e8080124fe</string>
</dict>
</plist>
